<template>
  <q-page class="q-pa-sm">
    <div class="row items-center q-mb-sm"><div><div class="text-subtitle1 text-weight-bold">Ventas</div><div class="text-caption text-grey-7">Resumen e historial de ventas</div></div><q-space/>
      <q-btn dense flat round color="primary" icon="refresh" :loading="loading" class="q-mr-xs" @click="load"><q-tooltip>Actualizar</q-tooltip></q-btn>
      <q-btn-dropdown dense flat color="primary" icon="download" label="Exportar" no-caps class="q-mr-xs"><q-list dense><q-item clickable v-close-popup @click="download('excel')"><q-item-section avatar><q-icon name="table_view" color="positive"/></q-item-section><q-item-section>Excel</q-item-section></q-item><q-item clickable v-close-popup @click="download('pdf')"><q-item-section avatar><q-icon name="picture_as_pdf" color="negative"/></q-item-section><q-item-section>PDF</q-item-section></q-item></q-list></q-btn-dropdown>
      <q-btn v-if="can('Crear Ventas')" dense unelevated color="positive" icon="add_shopping_cart" label="Nueva venta" no-caps to="/ventas/nueva"/>
    </div>

    <div class="row q-col-gutter-sm q-mb-sm">
      <div v-for="card in cards" :key="card.label" class="col-6 col-md-3"><q-card flat bordered :class="`summary-card bg-${card.color}-1 text-${card.color}-9`"><q-card-section class="row items-center q-pa-sm"><q-avatar :color="card.color" text-color="white" :icon="card.icon" size="36px"/><div class="q-ml-sm"><div class="text-caption">{{card.label}}</div><div class="text-h6 text-weight-bold">{{card.money?'Bs ':''}}{{card.money?money(card.value):card.value}}</div></div></q-card-section></q-card></div>
    </div>

    <q-card flat bordered>
      <q-card-section class="row q-col-gutter-sm q-pa-sm">
        <q-input v-model="search" dense outlined debounce="300" clearable placeholder="Buscar número, usuario o estado" class="col-12 col-md-4" @update:model-value="load"><template #prepend><q-icon name="search"/></template></q-input>
        <q-select v-model="user" :options="summary.usuarios" option-label="username" dense outlined clearable label="Usuario" class="col-6 col-md-2" @update:model-value="load"/>
        <q-select v-model="sendFilter" :options="sendFilterOptions" emit-value map-options dense outlined label="Envío SIAT" class="col-6 col-md-2" @update:model-value="load"/>
        <q-input v-model="from" dense outlined clearable type="date" label="Fecha desde" class="col-6 col-md-2" @update:model-value="load"/><q-input v-model="to" dense outlined clearable type="date" label="Fecha hasta" class="col-6 col-md-2" @update:model-value="load"/>
        <q-input v-model="timeFrom" dense outlined clearable type="time" label="Hora desde" class="col-6 col-md-2" @update:model-value="load"><template #prepend><q-icon name="schedule"/></template></q-input><q-input v-model="timeTo" dense outlined clearable type="time" label="Hora hasta" class="col-6 col-md-2" @update:model-value="load"><template #prepend><q-icon name="schedule"/></template></q-input>
        <div v-if="summary.facturas_rechazadas" class="col-12">
          <q-chip dense square clickable :color="sendFilter==='rechazadas'?'red-9':'red-2'" :text-color="sendFilter==='rechazadas'?'white':'red-10'" icon="gpp_bad" @click="toggleRejected">
            {{summary.facturas_rechazadas}} {{summary.facturas_rechazadas===1?'factura rechazada por Impuestos':'facturas rechazadas por Impuestos'}} · el cliente tiene un papel que no vale
            <q-tooltip>Se entregó la factura pero el SIN no la aceptó. Hay que corregir el dato y reenviarla. Clic para {{sendFilter==='rechazadas'?'quitar el filtro':'ver sólo estas ventas'}}.</q-tooltip>
          </q-chip>
        </div>
        <div v-if="summary.facturas_sin_emitir" class="col-12">
          <q-chip dense square clickable :color="sendFilter==='sin_emitir'?'deep-orange':'orange-2'" :text-color="sendFilter==='sin_emitir'?'white':'orange-10'" icon="receipt_long" @click="toggleUnissued">
            {{summary.facturas_sin_emitir}} {{summary.facturas_sin_emitir===1?'venta cobrada como factura que no se emitió':'ventas cobradas como factura que no se emitieron'}} · se entregó recibo
            <q-tooltip>Nunca llegaron a Impuestos, así que no tienen CUF. Clic para {{sendFilter==='sin_emitir'?'quitar el filtro':'ver sólo estas ventas'}}.</q-tooltip>
          </q-chip>
        </div>
      </q-card-section>
      <q-table dense flat :rows="rows" :columns="columns" row-key="id" :loading="loading" v-model:pagination="pagination" :rows-per-page-options="[20,50,100,200,0]" @request="onRequest">
        <template #body-cell-total="p"><q-td :props="p"><b>Bs {{money(p.value)}}</b></q-td></template>
        <template #body-cell-tipo_comprobante="p"><q-td :props="p"><q-chip dense square :color="p.value==='FACTURA'?'primary':'blue-grey'" text-color="white">{{p.value==='FACTURA'?'F':'R'}}<q-tooltip>{{p.value==='FACTURA'?'FACTURA':'RECIBO'}}</q-tooltip></q-chip></q-td></template>
        <template #body-cell-estado_siat="p"><q-td :props="p"><q-icon :name="taxStatus(p.row).icon" :color="taxStatus(p.row).color" size="19px"><q-tooltip>{{taxStatus(p.row).label}}<template v-if="p.row.siat_mensaje"> · {{p.row.siat_mensaje}}</template></q-tooltip></q-icon></q-td></template>
        <template #body-cell-online="p"><q-td :props="p"><q-icon :name="sendStatus(p.row).icon" :color="sendStatus(p.row).color" size="19px"><q-tooltip>{{sendStatus(p.row).label}}</q-tooltip></q-icon></q-td></template>
        <template #body-cell-cliente="p"><q-td :props="p"><template v-if="p.row.cliente_nombre"><div class="ellipsis cliente-nombre">{{p.row.cliente_nombre}}</div><div class="text-caption text-grey-7">{{p.row.tipo_documento}} {{p.row.numero_documento}}{{p.row.complemento?'-'+p.row.complemento:''}}</div><q-tooltip>{{p.row.cliente_nombre}}</q-tooltip></template><span v-else class="text-grey-6">Sin nombre</span></q-td></template>
        <template #body-cell-detalles="p"><q-td :props="p"><div class="items-list"><div v-for="d in (p.row.detalles||[])" :key="d.id" class="items-row"><b>{{qty(d.cantidad)}}{{d.unidad==='KG'?'kg':''}}</b> {{d.nombre}}</div><q-tooltip v-if="p.row.detalles?.length"><div v-for="d in p.row.detalles" :key="d.id">{{qty(d.cantidad)}}{{d.unidad==='KG'?'kg':''}} · {{d.nombre}}</div></q-tooltip></div></q-td></template>
        <template #body-cell-usuario="p"><q-td :props="p">{{p.row.usuario?.username||p.row.usuario_nombre}}</q-td></template>
        <template #body-cell-tipo_pago="p"><q-td :props="p"><q-chip dense square :color="paymentColor(p.value)" text-color="white">{{paymentInitial(p.value)}}<q-tooltip>{{p.value}}</q-tooltip></q-chip></q-td></template>
        <template #body-cell-estado="p"><q-td :props="p"><q-chip dense square :color="p.value==='COMPLETADA'?'positive':'negative'" text-color="white">{{p.value==='COMPLETADA'?'C':'A'}}<q-tooltip>{{p.value}}</q-tooltip></q-chip></q-td></template>
        <template #body-cell-actions="p"><q-td :props="p"><q-btn-dropdown dense flat color="primary" icon="more_vert" dropdown-icon="none"><q-list dense style="min-width:220px"><q-item clickable v-close-popup @click="showDetail(p.row)"><q-item-section avatar><q-icon name="visibility" color="primary"/></q-item-section><q-item-section>Ver detalle</q-item-section></q-item><q-item clickable v-close-popup @click="printRow(p.row)"><q-item-section avatar><q-icon name="print" color="blue-grey"/></q-item-section><q-item-section>Imprimir</q-item-section></q-item><template v-if="p.row.tipo_comprobante==='FACTURA'"><q-separator/><q-item clickable v-close-popup @click="verifyTaxes(p.row)"><q-item-section avatar><q-icon name="verified" color="positive"/></q-item-section><q-item-section>Verificar impuestos</q-item-section></q-item><q-item clickable v-close-popup @click="printTaxes(p.row)"><q-item-section avatar><q-icon name="receipt_long" color="primary"/></q-item-section><q-item-section>Imprimir impuestos</q-item-section></q-item><q-item v-if="packetReady(p.row)" clickable v-close-popup class="text-warning" @click="openEventDialog(p.row)"><q-item-section avatar><q-icon name="outbox"/></q-item-section><q-item-section>Enviar paquete</q-item-section></q-item><q-item v-if="packetReady(p.row)&&can('Corregir Fecha Factura SIAT')" clickable v-close-popup color="deep-orange" @click="openEventDialog(p.row,true)"><q-item-section avatar><q-icon name="edit_calendar" color="deep-orange"/></q-item-section><q-item-section class="text-deep-orange">Cambiar fecha y enviar</q-item-section></q-item><q-item v-if="unissued(p.row)&&can('Cambiar Factura a Recibo')" clickable v-close-popup @click="convertToReceipt(p.row)"><q-item-section avatar><q-icon name="swap_horiz" color="orange-9"/></q-item-section><q-item-section class="text-orange-9">Cambiar a RECIBO</q-item-section></q-item><q-item v-if="rejected(p.row)&&can('Corregir Factura Rechazada')" clickable v-close-popup @click="openFixDialog(p.row)"><q-item-section avatar><q-icon name="gpp_bad" color="red-9"/></q-item-section><q-item-section class="text-red-9">Corregir documento y reenviar</q-item-section></q-item></template><q-separator/><q-item v-if="can('Anular Ventas')&&p.row.estado==='COMPLETADA'" clickable v-close-popup class="text-negative" @click="cancel(p.row)"><q-item-section avatar><q-icon name="cancel"/></q-item-section><q-item-section>Anular</q-item-section></q-item></q-list></q-btn-dropdown></q-td></template>
      </q-table>
    </q-card>

    <q-dialog v-model="dialog"><q-card style="width:760px;max-width:96vw"><q-card-section class="row items-center q-py-sm"><div><div class="text-subtitle1 text-weight-bold">{{selected.numero}}</div><div class="text-caption">{{formatDate(selected.fecha)}} · {{selected.usuario_nombre}}</div></div><q-space/><q-btn flat round dense icon="print" color="primary" @click="printSale(selected)"/><q-badge :color="selected.estado==='COMPLETADA'?'positive':'negative'" :label="selected.estado"/><q-btn flat round dense icon="close" v-close-popup/></q-card-section><q-separator/><q-table dense flat :rows="selected.detalles||[]" :columns="detailColumns" row-key="id" hide-pagination :rows-per-page-options="[0]"><template #body-cell-total="p"><q-td :props="p">Bs {{money(p.value)}}</q-td></template></q-table><q-separator/><q-card-section class="q-pa-sm"><div class="row"><span>Subtotal</span><q-space/>Bs {{money(selected.subtotal)}}</div><div class="row text-negative"><span>Descuento</span><q-space/>- Bs {{money(selected.descuento)}}</div><div class="row"><span>Efectivo</span><q-space/>Bs {{money(selected.monto_efectivo)}}</div><div class="row"><span>QR</span><q-space/>Bs {{money(selected.monto_qr)}}</div><div class="row text-h6 text-primary"><b>Total</b><q-space/><b>Bs {{money(selected.total)}}</b></div></q-card-section></q-card></q-dialog>
    <q-dialog v-model="reasonsDialog"><q-card style="width:600px;max-width:96vw"><q-card-section class="row items-center"><div class="text-h6">Motivo de anulación</div><q-space/><q-btn flat round dense icon="close" v-close-popup/></q-card-section><q-separator/><q-list separator><q-item v-for="reason in cancellationReasons" :key="reason.codigo" clickable @click="cancelWithReason(reason)"><q-item-section avatar><q-avatar color="primary" text-color="white" size="30px">{{reason.codigo}}</q-avatar></q-item-section><q-item-section>{{reason.descripcion}}</q-item-section><q-item-section side><q-icon name="chevron_right"/></q-item-section></q-item></q-list></q-card></q-dialog>
    <q-dialog v-model="eventDialog"><q-card style="width:560px;max-width:96vw"><q-form @submit.prevent="processEvent"><q-card-section class="row items-center q-py-sm"><q-avatar color="warning" text-color="white" icon="wifi_off"/><div class="q-ml-sm"><div class="text-subtitle1 text-weight-bold">Evento significativo</div><div class="text-caption text-grey-7">Enviar únicamente la factura {{eventForm.saleNumber}}</div></div><q-space/><q-btn flat round dense icon="close" v-close-popup/></q-card-section><q-separator/><q-card-section class="row q-col-gutter-sm"><q-select v-model="eventForm.reason" :options="eventReasons" option-label="descripcion" outlined dense label="Motivo del evento" class="col-12" :rules="[v=>!!v||'Seleccione un motivo']" @update:model-value="reason=>eventForm.description=reason?.descripcion||''"/><q-input v-model="eventForm.description" outlined dense label="Descripción" class="col-12" :rules="[v=>!!v||'Requerido']"/><template v-if="can('Corregir Fecha Factura SIAT')"><q-toggle v-model="eventForm.correctDate" color="warning" label="Corregir fecha de emisión antes de enviar" class="col-12"/><q-input v-if="eventForm.correctDate" v-model="eventForm.emissionDate" type="datetime-local" step="1" outlined dense label="Nueva fecha de emisión" class="col-12" :rules="[v=>!!v||'Requerido']"><template #prepend><q-icon name="edit_calendar"/></template></q-input></template><q-banner rounded class="col-12 bg-orange-1 text-orange-10"><q-icon name="info" class="q-mr-xs"/>Se enviará sólo esta factura. El rango del evento se calculará automáticamente segundo a segundo.</q-banner></q-card-section><q-separator/><q-card-actions align="right"><q-btn flat label="Cancelar" no-caps v-close-popup/><q-btn type="submit" unelevated color="warning" text-color="white" icon="send" label="Registrar y enviar" no-caps :loading="eventLoading"/></q-card-actions></q-form></q-card></q-dialog>
    <q-dialog v-model="fixDialog"><q-card style="width:560px;max-width:96vw"><q-form @submit.prevent="submitFix"><q-card-section class="row items-center q-py-sm"><q-avatar color="red-9" text-color="white" icon="gpp_bad"/><div class="q-ml-sm"><div class="text-subtitle1 text-weight-bold">Corregir factura rechazada</div><div class="text-caption text-grey-7">{{fixForm.numero}} · Bs {{money(fixForm.total)}}</div></div><q-space/><q-btn flat round dense icon="close" v-close-popup/></q-card-section><q-separator/><q-card-section class="row q-col-gutter-sm"><q-banner rounded class="col-12 bg-red-1 text-red-10"><q-icon name="error_outline" class="q-mr-xs"/>Impuestos rechazó esta factura: <b>{{fixForm.motivo||'sin detalle'}}</b></q-banner><q-select v-model="fixForm.tipo_documento" :options="['CI','NIT']" outlined dense label="Tipo de documento" class="col-4" :rules="[v=>!!v||'Requerido']"/><q-input v-model="fixForm.numero_documento" outlined dense label="Número de documento" class="col-5" :rules="[v=>!!v&&v!=='0'||'Requerido']"/><q-input v-model="fixForm.complemento" outlined dense label="Compl." class="col-3"/><q-input v-model="fixForm.cliente_nombre" outlined dense label="Nombre o razón social" class="col-12" :rules="[v=>!!v||'Requerido']"/><q-input v-model="fixForm.cliente_email" outlined dense type="email" label="Correo (opcional)" class="col-12"/><q-banner rounded class="col-12 bg-blue-1 text-blue-10"><q-icon name="info" class="q-mr-xs"/>Se emitirá de nuevo con el mismo número de factura y la fecha de hoy. El monto y los productos no cambian.</q-banner></q-card-section><q-separator/><q-card-actions align="right"><q-btn flat label="Cancelar" no-caps v-close-popup/><q-btn type="submit" unelevated color="red-9" icon="send" label="Corregir y reenviar" no-caps :loading="fixLoading"/></q-card-actions></q-form></q-card></q-dialog>
  </q-page>
</template>

<script setup>
import {computed,getCurrentInstance,reactive,ref} from 'vue'
import {openSiatInvoice,printSale} from '../../addons/ventaPrint'
// La pantalla arranca filtrada al día de hoy completo.
const hoy=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const HORA_INICIO='00:01',HORA_FIN='23:59'
const {proxy}=getCurrentInstance(),rows=ref([]),loading=ref(false),search=ref(''),from=ref(hoy()),to=ref(hoy()),timeFrom=ref(HORA_INICIO),timeTo=ref(HORA_FIN),user=ref(null),sendFilter=ref(null),dialog=ref(false),selected=reactive({}),reasonsDialog=ref(false),taxSale=ref(null),eventDialog=ref(false),eventLoading=ref(false),eventReasons=ref([]),summary=reactive({efectivo:0,qr:0,total:0,descuento:0,cantidad:0,facturas_sin_emitir:0,facturas_rechazadas:0,usuarios:[]})
const fixDialog=ref(false),fixLoading=ref(false),fixForm=reactive({id:null,numero:'',total:0,motivo:'',tipo_documento:'CI',numero_documento:'',complemento:'',cliente_nombre:'',cliente_email:''})
const sendFilterOptions=[{label:'Todos',value:null},{label:'Faltan enviar',value:'pendientes'},{label:'Enviadas',value:'enviadas'},{label:'Sin emitir',value:'sin_emitir'},{label:'Rechazadas',value:'rechazadas'}]
const eventForm=reactive({reason:null,description:'',saleId:null,saleNumber:'',correctDate:false,emissionDate:''})
const cancellationReasons=[{codigo:1,descripcion:'FACTURA MAL EMITIDA'},{codigo:2,descripcion:'NOTA DE CRÉDITO-DÉBITO MAL EMITIDA'},{codigo:3,descripcion:'DATOS DE EMISIÓN INCORRECTOS'},{codigo:4,descripcion:'FACTURA O NOTA DE CRÉDITO-DÉBITO DEVUELTA'}]
const pagination=ref({page:1,rowsPerPage:50,rowsNumber:0}),money=v=>Number(v||0).toFixed(2),can=p=>proxy.$store.hasPermission(p)
const cards=computed(()=>[{label:'Total vendido',value:summary.total,money:true,icon:'trending_up',color:'primary'},{label:'Efectivo',value:summary.efectivo,money:true,icon:'payments',color:'green'},{label:'QR',value:summary.qr,money:true,icon:'qr_code_2',color:'blue'},{label:'Ventas',value:summary.cantidad,money:false,icon:'receipt_long',color:'purple'}])
const columns=[{name:'actions',label:'',align:'left'},{name:'numero',label:'Nº venta',field:'numero',align:'left'},{name:'tipo_comprobante',label:'Comprobante',field:'tipo_comprobante',align:'center'},{name:'online',label:'Envío',field:'online',align:'center'},{name:'estado_siat',label:'Validez',field:'estado_siat',align:'center'},{name:'fecha',label:'Fecha',field:r=>formatDate(r.fecha),align:'left'},{name:'cliente',label:'Facturado a',field:'cliente_nombre',align:'left'},{name:'usuario',label:'Usuario',field:'usuario_nombre',align:'left'},{name:'tipo_pago',label:'Pago',field:'tipo_pago',align:'center'},{name:'detalles',label:'Productos',field:'detalles_count',align:'left'},{name:'descuento',label:'Descuento',field:'descuento',format:v=>`Bs ${money(v)}`,align:'right'},{name:'total',label:'Total',field:'total',align:'right'},{name:'estado',label:'Estado',field:'estado',align:'center'}]
const detailColumns=[{name:'codigo',label:'Código',field:'codigo',align:'left'},{name:'nombre',label:'Producto',field:'nombre',align:'left'},{name:'cantidad',label:'Cant.',field:'cantidad',align:'center'},{name:'precio',label:'Precio',field:'precio_venta',format:v=>`Bs ${money(v)}`,align:'right'},{name:'total',label:'Total',field:'total',align:'right'}]
const params=()=>({q:search.value,desde:from.value,hasta:to.value,hora_desde:timeFrom.value,hora_hasta:timeTo.value,user_id:user.value?.id,envio:sendFilter.value}),paymentColor=v=>v==='EFECTIVO'?'green':v==='QR'?'blue':'purple',paymentInitial=v=>v==='EFECTIVO'?'E':v==='QR'?'Q':'C'
// Cantidad sin ceros de relleno: 2, 1.5, 1.655.
const qty=v=>{const n=Number(v||0);return Number.isInteger(n)?String(n):String(parseFloat(n.toFixed(3)))}
const packetReady=row=>row.tipo_comprobante==='FACTURA'&&!row.online&&row.estado_siat==='PENDIENTE_EVENTO'&&row.cuf&&row.xml_path&&row.fecha_emision_siat
// Cobrada como factura pero sin CUF: nunca se emitió en Impuestos.
const unissued=row=>row.tipo_comprobante==='FACTURA'&&!row.cuf&&row.estado==='COMPLETADA'
// Factura entregada al cliente que Impuestos rechazó: hay que corregirla y reenviarla.
const rejected=row=>row.tipo_comprobante==='FACTURA'&&row.estado_siat==='OBSERVADA'&&row.estado==='COMPLETADA'
function toggleUnissued(){sendFilter.value=sendFilter.value==='sin_emitir'?null:'sin_emitir';load()}
function toggleRejected(){sendFilter.value=sendFilter.value==='rechazadas'?null:'rechazadas';load()}
// Se propone el tipo contrario al rechazado: el error típico es cargar un CI como NIT.
function openFixDialog(row){Object.assign(fixForm,{id:row.id,numero:row.numero,total:row.total,motivo:row.siat_mensaje,tipo_documento:row.tipo_documento==='NIT'?'CI':'NIT',numero_documento:row.numero_documento||'',complemento:row.complemento||'',cliente_nombre:row.cliente_nombre||'',cliente_email:row.cliente_email||''});fixDialog.value=true}
async function submitFix(){fixLoading.value=true;try{const{data}=await proxy.$axios.put(`/ventas/${fixForm.id}/corregir-factura`,{tipo_documento:fixForm.tipo_documento,numero_documento:fixForm.numero_documento,complemento:fixForm.complemento||null,cliente_nombre:fixForm.cliente_nombre,cliente_email:fixForm.cliente_email||null});if(data.aceptada){fixDialog.value=false;proxy.$alert.success(data.mensaje)}else{proxy.$alert.error(data.mensaje)}load()}catch(e){proxy.$alert.error(e.response?.data?.message||'No se pudo reenviar la factura')}finally{fixLoading.value=false}}
function convertToReceipt(row){proxy.$alert.dialog('Cambiar a RECIBO',`La venta ${row.numero} quedó marcada como factura pero nunca se emitió en Impuestos. ¿Convertirla en recibo? El monto y el stock no cambian.`).onOk(()=>proxy.$axios.put(`/ventas/${row.id}/convertir-recibo`).then(({data})=>{proxy.$alert.success(data.mensaje);load()}).catch(e=>proxy.$alert.error(e.response?.data?.message||'No se pudo cambiar el tipo de comprobante')))}
function sendStatus(row){if(row.tipo_comprobante!=='FACTURA')return{label:'NO APLICA',color:'blue-grey',icon:'remove'};if(row.online)return{label:'ENVIADA',color:'positive',icon:'cloud_done'};return packetReady(row)?{label:'FALTA ENVIAR',color:'warning',icon:'cloud_upload'}:{label:'NO PREPARADA',color:'negative',icon:'error_outline'}}
function taxStatus(row){
  if(row.tipo_comprobante!=='FACTURA')return{label:'NO APLICA',color:'blue-grey',icon:'remove_circle_outline'}
  const statuses={VALIDADA:{label:'VÁLIDA',color:'positive',icon:'verified'},OBSERVADA:{label:'OBSERVADA',color:'negative',icon:'error'},ANULADA:{label:'ANULADA',color:'dark',icon:'block'},ENVIANDO:{label:'ENVIANDO',color:'info',icon:'sync'},PENDIENTE_EVENTO:{label:'PENDIENTE',color:'warning',icon:'schedule'},PENDIENTE_CONFIGURACION:{label:'PENDIENTE',color:'warning',icon:'settings'}}
  return statuses[row.estado_siat]||{label:row.estado_siat||'PENDIENTE',color:'warning',icon:'schedule'}
}
function formatDate(v){return v?new Date(v).toLocaleString('es-BO'):''}function load(){onRequest({pagination:pagination.value})}function loadSummary(){proxy.$axios.get('/ventas-resumen',{params:params()}).then(r=>Object.assign(summary,r.data))}
function onRequest({pagination:p}){loading.value=true;proxy.$axios.get('/ventas',{params:{...params(),page:p.page,per_page:p.rowsPerPage}}).then(r=>{rows.value=r.data.data;pagination.value={...p,rowsNumber:r.data.total};loadSummary()}).catch(e=>proxy.$alert.error(e.response?.data?.message||'No se pudieron cargar las ventas')).finally(()=>loading.value=false)}
function showDetail(row){proxy.$axios.get(`/ventas/${row.id}`).then(r=>{Object.assign(selected,r.data);dialog.value=true})}function printRow(row){proxy.$axios.get(`/ventas/${row.id}`).then(r=>printSale(r.data))}
async function verifyTaxes(row){try{const {data}=await proxy.$axios.get(`/ventas/${row.id}/verificar-impuestos`);proxy.$alert.success(`SIAT ${data.codigo_estado||''}: ${data.mensaje}`);load()}catch(e){proxy.$alert.error(e.response?.data?.message||'No se pudo verificar la factura en SIAT')}}
function printTaxes(row){try{openSiatInvoice(row)}catch(e){proxy.$alert.error(e.message||'No se pudo abrir la factura en Impuestos')}}
function cancel(row){if(row.tipo_comprobante==='FACTURA'&&row.estado_siat==='VALIDADA'){taxSale.value=row;reasonsDialog.value=true;return}confirmCancellation(row)}
function cancelWithReason(reason){reasonsDialog.value=false;confirmCancellation(taxSale.value,reason)}
function confirmCancellation(row,reason=null){const detail=reason?` Motivo: ${reason.descripcion}.`:'';proxy.$alert.dialog(`¿Anular ${row.tipo_comprobante.toLowerCase()} ${row.numero}?${detail} El stock será restaurado.`).onOk(()=>proxy.$axios.put(`/ventas/${row.id}/anular`,reason?{codigo_motivo:reason.codigo}:{}).then(({data})=>{proxy.$alert.success(data.mensaje||'Venta anulada correctamente');load()}).catch(e=>proxy.$alert.error(e.response?.data?.message||'No se pudo anular')))}
async function openEventDialog(row,correctDate=false){if(!row)return;try{const{data}=await proxy.$axios.get('/siat-eventos-significativos');eventReasons.value=data.motivos;const center=new Date(row.fecha_emision_siat||row.fecha),local=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,19);eventForm.saleId=row.id;eventForm.saleNumber=row.numero;eventForm.correctDate=correctDate&&can('Corregir Fecha Factura SIAT');eventForm.emissionDate=local(center);eventForm.reason=eventReasons.value.find(i=>i.codigo===2)||eventReasons.value[0];eventForm.description=eventForm.reason?.descripcion||'';eventDialog.value=true}catch(e){proxy.$alert.error(e.response?.data?.message||'No se pudo preparar el evento significativo')}}
async function processEvent(){eventLoading.value=true;try{const payload={codigo_motivo:eventForm.reason.codigo,descripcion:eventForm.description,venta_id:eventForm.saleId};if(eventForm.correctDate)payload.fecha_emision=eventForm.emissionDate;const{data}=await proxy.$axios.post('/siat-eventos-significativos',payload);eventDialog.value=false;proxy.$alert.success(`Evento ${data.codigo_evento}: factura enviada correctamente`);load()}catch(e){proxy.$alert.error(e.response?.data?.message||'No se pudo procesar el evento significativo')}finally{eventLoading.value=false}}
async function download(type){try{const response=await proxy.$axios.get(`/ventas-exportar/${type}`,{params:params(),responseType:'blob'});const url=URL.createObjectURL(response.data),a=document.createElement('a');a.href=url;a.download=`ventas.${type==='excel'?'xlsx':'pdf'}`;a.click();URL.revokeObjectURL(url)}catch{proxy.$alert.error('No se pudo exportar el reporte')}}
load()
</script>

<style scoped>.summary-card{border-radius:10px}.cliente-nombre{max-width:220px;line-height:1.2}
.items-list{max-width:280px;padding:1px 0}
.items-row{font-size:9px;line-height:1;color:#5f5f5f;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.items-row b{color:#1d1d1d}</style>
