<template>
  <q-page class="q-pa-sm">
    <div class="row items-center q-mb-sm"><div><div class="text-subtitle1 text-weight-bold">Ventas</div><div class="text-caption text-grey-7">Resumen e historial de ventas</div></div><q-space/>
      <q-btn-dropdown dense flat color="primary" icon="download" label="Exportar" no-caps class="q-mr-xs"><q-list dense><q-item clickable v-close-popup @click="download('excel')"><q-item-section avatar><q-icon name="table_view" color="positive"/></q-item-section><q-item-section>Excel</q-item-section></q-item><q-item clickable v-close-popup @click="download('pdf')"><q-item-section avatar><q-icon name="picture_as_pdf" color="negative"/></q-item-section><q-item-section>PDF</q-item-section></q-item></q-list></q-btn-dropdown>
      <q-btn v-if="can('Crear Ventas')" dense unelevated color="positive" icon="add_shopping_cart" label="Nueva venta" no-caps to="/ventas/nueva"/>
    </div>

    <div class="row q-col-gutter-sm q-mb-sm">
      <div v-for="card in cards" :key="card.label" class="col-6 col-md-3"><q-card flat bordered :class="`summary-card bg-${card.color}-1 text-${card.color}-9`"><q-card-section class="row items-center q-pa-sm"><q-avatar :color="card.color" text-color="white" :icon="card.icon" size="36px"/><div class="q-ml-sm"><div class="text-caption">{{card.label}}</div><div class="text-h6 text-weight-bold">{{card.money?'Bs ':''}}{{card.money?money(card.value):card.value}}</div></div></q-card-section></q-card></div>
    </div>

    <q-card flat bordered>
      <q-card-section class="row q-col-gutter-sm q-pa-sm">
        <q-input v-model="search" dense outlined debounce="300" clearable placeholder="Buscar número, usuario o estado" class="col-12 col-md-4" @update:model-value="load"><template #prepend><q-icon name="search"/></template></q-input>
        <q-select v-model="user" :options="summary.usuarios" option-label="username" dense outlined clearable label="Usuario" class="col-12 col-md-3" @update:model-value="load"/>
        <q-input v-model="from" dense outlined type="date" label="Desde" class="col-6 col-md-2" @update:model-value="load"/><q-input v-model="to" dense outlined type="date" label="Hasta" class="col-6 col-md-2" @update:model-value="load"/>
      </q-card-section>
      <q-table dense flat :rows="rows" :columns="columns" row-key="id" :loading="loading" v-model:pagination="pagination" :rows-per-page-options="[10,20,50,100,0]" @request="onRequest">
        <template #body-cell-total="p"><q-td :props="p"><b>Bs {{money(p.value)}}</b></q-td></template>
        <template #body-cell-tipo_comprobante="p"><q-td :props="p"><q-chip dense square :color="p.value==='FACTURA'?'primary':'blue-grey'" text-color="white">{{p.value==='FACTURA'?'F':'R'}}<q-tooltip>{{p.value==='FACTURA'?'FACTURA':'RECIBO'}}</q-tooltip></q-chip></q-td></template>
        <template #body-cell-estado_siat="p"><q-td :props="p"><q-chip dense square :color="taxStatus(p.row).color" text-color="white" :icon="taxStatus(p.row).icon">{{taxStatus(p.row).label}}<q-tooltip v-if="p.row.siat_mensaje">{{p.row.siat_mensaje}}</q-tooltip></q-chip></q-td></template>
        <template #body-cell-usuario="p"><q-td :props="p">{{p.row.usuario?.username||p.row.usuario_nombre}}</q-td></template>
        <template #body-cell-tipo_pago="p"><q-td :props="p"><q-chip dense square :color="paymentColor(p.value)" text-color="white">{{paymentInitial(p.value)}}<q-tooltip>{{p.value}}</q-tooltip></q-chip></q-td></template>
        <template #body-cell-estado="p"><q-td :props="p"><q-chip dense square :color="p.value==='COMPLETADA'?'positive':'negative'" text-color="white">{{p.value==='COMPLETADA'?'C':'A'}}<q-tooltip>{{p.value}}</q-tooltip></q-chip></q-td></template>
        <template #body-cell-actions="p"><q-td :props="p"><q-btn-dropdown dense flat color="primary" icon="more_vert" dropdown-icon="none"><q-list dense style="min-width:220px"><q-item clickable v-close-popup @click="showDetail(p.row)"><q-item-section avatar><q-icon name="visibility" color="primary"/></q-item-section><q-item-section>Ver detalle</q-item-section></q-item><q-item clickable v-close-popup @click="printRow(p.row)"><q-item-section avatar><q-icon name="print" color="blue-grey"/></q-item-section><q-item-section>Imprimir</q-item-section></q-item><template v-if="p.row.tipo_comprobante==='FACTURA'"><q-separator/><q-item clickable v-close-popup @click="verifyTaxes(p.row)"><q-item-section avatar><q-icon name="verified" color="positive"/></q-item-section><q-item-section>Verificar impuestos</q-item-section></q-item><q-item clickable v-close-popup @click="printTaxes(p.row)"><q-item-section avatar><q-icon name="receipt_long" color="primary"/></q-item-section><q-item-section>Imprimir impuestos</q-item-section></q-item></template><q-separator/><q-item v-if="can('Anular Ventas')&&p.row.estado==='COMPLETADA'" clickable v-close-popup class="text-negative" @click="cancel(p.row)"><q-item-section avatar><q-icon name="cancel"/></q-item-section><q-item-section>Anular</q-item-section></q-item></q-list></q-btn-dropdown></q-td></template>
      </q-table>
    </q-card>

    <q-dialog v-model="dialog"><q-card style="width:760px;max-width:96vw"><q-card-section class="row items-center q-py-sm"><div><div class="text-subtitle1 text-weight-bold">{{selected.numero}}</div><div class="text-caption">{{formatDate(selected.fecha)}} · {{selected.usuario_nombre}}</div></div><q-space/><q-btn flat round dense icon="print" color="primary" @click="printSale(selected)"/><q-badge :color="selected.estado==='COMPLETADA'?'positive':'negative'" :label="selected.estado"/><q-btn flat round dense icon="close" v-close-popup/></q-card-section><q-separator/><q-table dense flat :rows="selected.detalles||[]" :columns="detailColumns" row-key="id" hide-pagination :rows-per-page-options="[0]"><template #body-cell-total="p"><q-td :props="p">Bs {{money(p.value)}}</q-td></template></q-table><q-separator/><q-card-section class="q-pa-sm"><div class="row"><span>Subtotal</span><q-space/>Bs {{money(selected.subtotal)}}</div><div class="row text-negative"><span>Descuento</span><q-space/>- Bs {{money(selected.descuento)}}</div><div class="row"><span>Efectivo</span><q-space/>Bs {{money(selected.monto_efectivo)}}</div><div class="row"><span>QR</span><q-space/>Bs {{money(selected.monto_qr)}}</div><div class="row text-h6 text-primary"><b>Total</b><q-space/><b>Bs {{money(selected.total)}}</b></div></q-card-section></q-card></q-dialog>
    <q-dialog v-model="reasonsDialog"><q-card style="width:600px;max-width:96vw"><q-card-section class="row items-center"><div class="text-h6">Motivo de anulación</div><q-space/><q-btn flat round dense icon="close" v-close-popup/></q-card-section><q-separator/><q-list separator><q-item v-for="reason in cancellationReasons" :key="reason.codigo" clickable @click="cancelWithReason(reason)"><q-item-section avatar><q-avatar color="primary" text-color="white" size="30px">{{reason.codigo}}</q-avatar></q-item-section><q-item-section>{{reason.descripcion}}</q-item-section><q-item-section side><q-icon name="chevron_right"/></q-item-section></q-item></q-list></q-card></q-dialog>
  </q-page>
</template>

<script setup>
import {computed,getCurrentInstance,reactive,ref} from 'vue'
import {printSale} from '../../addons/ventaPrint'
const {proxy}=getCurrentInstance(),rows=ref([]),loading=ref(false),search=ref(''),from=ref(''),to=ref(''),user=ref(null),dialog=ref(false),selected=reactive({}),reasonsDialog=ref(false),taxSale=ref(null),summary=reactive({efectivo:0,qr:0,total:0,descuento:0,cantidad:0,usuarios:[]})
const cancellationReasons=[{codigo:1,descripcion:'FACTURA MAL EMITIDA'},{codigo:2,descripcion:'NOTA DE CRÉDITO-DÉBITO MAL EMITIDA'},{codigo:3,descripcion:'DATOS DE EMISIÓN INCORRECTOS'},{codigo:4,descripcion:'FACTURA O NOTA DE CRÉDITO-DÉBITO DEVUELTA'}]
const pagination=ref({page:1,rowsPerPage:20,rowsNumber:0}),money=v=>Number(v||0).toFixed(2),can=p=>proxy.$store.hasPermission(p)
const cards=computed(()=>[{label:'Total vendido',value:summary.total,money:true,icon:'trending_up',color:'primary'},{label:'Efectivo',value:summary.efectivo,money:true,icon:'payments',color:'green'},{label:'QR',value:summary.qr,money:true,icon:'qr_code_2',color:'blue'},{label:'Ventas',value:summary.cantidad,money:false,icon:'receipt_long',color:'purple'}])
const columns=[{name:'actions',label:'',align:'left'},{name:'numero',label:'Nº venta',field:'numero',align:'left'},{name:'tipo_comprobante',label:'Comprobante',field:'tipo_comprobante',align:'center'},{name:'estado_siat',label:'Validez SIAT',field:'estado_siat',align:'center'},{name:'fecha',label:'Fecha',field:r=>formatDate(r.fecha),align:'left'},{name:'usuario',label:'Usuario',field:'usuario_nombre',align:'left'},{name:'tipo_pago',label:'Pago',field:'tipo_pago',align:'center'},{name:'detalles',label:'Productos',field:'detalles_count',align:'center'},{name:'descuento',label:'Descuento',field:'descuento',format:v=>`Bs ${money(v)}`,align:'right'},{name:'total',label:'Total',field:'total',align:'right'},{name:'estado',label:'Estado',field:'estado',align:'center'}]
const detailColumns=[{name:'codigo',label:'Código',field:'codigo',align:'left'},{name:'nombre',label:'Producto',field:'nombre',align:'left'},{name:'cantidad',label:'Cant.',field:'cantidad',align:'center'},{name:'precio',label:'Precio',field:'precio_venta',format:v=>`Bs ${money(v)}`,align:'right'},{name:'total',label:'Total',field:'total',align:'right'}]
const params=()=>({q:search.value,desde:from.value,hasta:to.value,user_id:user.value?.id}),paymentColor=v=>v==='EFECTIVO'?'green':v==='QR'?'blue':'purple',paymentInitial=v=>v==='EFECTIVO'?'E':v==='QR'?'Q':'C'
function taxStatus(row){
  if(row.tipo_comprobante!=='FACTURA')return{label:'NO APLICA',color:'blue-grey',icon:'remove_circle_outline'}
  const statuses={VALIDADA:{label:'VÁLIDA',color:'positive',icon:'verified'},OBSERVADA:{label:'OBSERVADA',color:'negative',icon:'error'},ANULADA:{label:'ANULADA',color:'dark',icon:'block'},ENVIANDO:{label:'ENVIANDO',color:'info',icon:'sync'},PENDIENTE_EVENTO:{label:'PENDIENTE',color:'warning',icon:'schedule'},PENDIENTE_CONFIGURACION:{label:'PENDIENTE',color:'warning',icon:'settings'}}
  return statuses[row.estado_siat]||{label:row.estado_siat||'PENDIENTE',color:'warning',icon:'schedule'}
}
function formatDate(v){return v?new Date(v).toLocaleString('es-BO'):''}function load(){onRequest({pagination:pagination.value})}function loadSummary(){proxy.$axios.get('/ventas-resumen',{params:params()}).then(r=>Object.assign(summary,r.data))}
function onRequest({pagination:p}){loading.value=true;proxy.$axios.get('/ventas',{params:{...params(),page:p.page,per_page:p.rowsPerPage}}).then(r=>{rows.value=r.data.data;pagination.value={...p,rowsNumber:r.data.total};loadSummary()}).catch(e=>proxy.$alert.error(e.response?.data?.message||'No se pudieron cargar las ventas')).finally(()=>loading.value=false)}
function showDetail(row){proxy.$axios.get(`/ventas/${row.id}`).then(r=>{Object.assign(selected,r.data);dialog.value=true})}function printRow(row){proxy.$axios.get(`/ventas/${row.id}`).then(r=>printSale(r.data))}
async function verifyTaxes(row){try{const {data}=await proxy.$axios.get(`/ventas/${row.id}/verificar-impuestos`);proxy.$alert.success(`SIAT ${data.codigo_estado||''}: ${data.mensaje}`);load()}catch(e){proxy.$alert.error(e.response?.data?.message||'No se pudo verificar la factura en SIAT')}}
function printTaxes(row){proxy.$axios.get(`/ventas/${row.id}`).then(({data})=>printSale(data)).catch(e=>proxy.$alert.error(e.response?.data?.message||'No se pudo imprimir la factura'))}
function cancel(row){if(row.tipo_comprobante==='FACTURA'&&row.estado_siat==='VALIDADA'){taxSale.value=row;reasonsDialog.value=true;return}confirmCancellation(row)}
function cancelWithReason(reason){reasonsDialog.value=false;confirmCancellation(taxSale.value,reason)}
function confirmCancellation(row,reason=null){const detail=reason?` Motivo: ${reason.descripcion}.`:'';proxy.$alert.dialog(`¿Anular ${row.tipo_comprobante.toLowerCase()} ${row.numero}?${detail} El stock será restaurado.`).onOk(()=>proxy.$axios.put(`/ventas/${row.id}/anular`,reason?{codigo_motivo:reason.codigo}:{}).then(({data})=>{proxy.$alert.success(data.mensaje||'Venta anulada correctamente');load()}).catch(e=>proxy.$alert.error(e.response?.data?.message||'No se pudo anular')))}
async function download(type){try{const response=await proxy.$axios.get(`/ventas-exportar/${type}`,{params:params(),responseType:'blob'});const url=URL.createObjectURL(response.data),a=document.createElement('a');a.href=url;a.download=`ventas.${type==='excel'?'xlsx':'pdf'}`;a.click();URL.revokeObjectURL(url)}catch{proxy.$alert.error('No se pudo exportar el reporte')}}
load()
</script>

<style scoped>.summary-card{border-radius:10px}</style>
